on:
  push:
    branches:
      - main
      - v1

name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ðŸ“‚ Sync files
      env:
          OVH_SSH_HOST: ${{ secrets.OVH_SSH_HOST }}
          OVH_SSH_PORT: ${{ secrets.OVH_SSH_PORT }}
          OVH_SSH_USERNAME: ${{ secrets.OVH_SSH_USERNAME }}
          OVH_SSH_PASSWORD: ${{ secrets.OVH_SSH_PASSWORD }}
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.cluster051.hosting.ovh.net
        username: nomadmt
        password: ${{ secrets.OVH_SSH_PASSWORD }}
        local-dir: client/build/
        server-dir: /www/